services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        # Movies
        App\Movies\UserInterface\ApiPlatform\Serializer\Normalizer\MovieResourceNormalizer:
            tags:
                - { name: serializer.normalizer, priority: 256 }
        
        App\Movies\UserInterface\ApiPlatform\Serializer\Denormalize\CreateMovieResourceNormalizer:
            tags: [ serializer.normalizer ]
        # Ratings 
        App\Ratings\UserInterface\ApiPlatform\Serializer\Normalizer\RatingResourceNormalizer:
            tags:
                - { name: serializer.normalizer, priority: 256 }

        # Messenger handlers
        App\Common\Application\Query\QueryHandler:
            tags:
                - { name: 'messenger.message_handler', bus: 'query.bus' }

        App\Common\Application\Command\CommandHandler:
            tags:
                - { name: 'messenger.message_handler', bus: 'command.bus' }

    # Common
    App\Common\:
        resource: '%kernel.project_dir%/src/Common/'
        exclude:
            - '%kernel.project_dir%/src/Common/Infrastructure/Symfony/Kernel.php'

    # Movies
    App\Movies\:
        resource: '%kernel.project_dir%/src/Movies/'
    
    # Ratings
    App\Ratings\:
        resource: '%kernel.project_dir%/src/Ratings/'

    # Doctrine
    App\Movies\Domain\Repository\MovieRepository:
        alias: App\Movies\Infrastructure\Doctrine\Repository\DoctrineMovieRepository
    App\Ratings\Domain\Repository\RatingRepository:
        alias: App\Ratings\Infrastructure\Doctrine\Repository\DoctrineRatingRepository
        
    # InMemory
    # App\Movies\Domain\Repository\MovieRepository:
    #     alias: App\Movies\Infrastructure\InMemory\InMemoryMovieRepository

    # App\Ratings\Domain\Repository\RatingRepository:
    #     alias: App\Ratings\Infrastructure\InMemory\InMemoryRatingRepository
