api:
  dashboard: true

global:
  sendAnonymousUsage: false

log:
  level: "WARN"
  format: "common"

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: true
  https:
    address: ":443"

providers:
  file:
    filename: /etc/traefik/traefik.config.yml
